version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c_captcher
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    networks:
      - bot_network

networks:
  bot_network:
